### ISSUE TITLE
Time drift: ACM ValidationException: You can Import a certificate only during its validity period.

### ISSUE THREAD

**Issue by gft-tuhg** [cloudposse/terraform-aws-ssm-tls-self-signed-cert#8] opened 2021-10-02 04:24 UTC
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
I'm having trouble creating and importing a certificate to AWS ACM. Here is the error output I received:
```
│ Error: error importing ACM Certificate: ValidationException: The certificate is valid in the future. You can Import a certificate only during its validity period.
│
│   with module.self_signed_cert_server.aws_acm_certificate.default[0],
│   on .terraform/modules/self_signed_cert_server/acm.tf line 1, in resource "aws_acm_certificate" "default":
│    1: resource "aws_acm_certificate" "default" {
```
which halted my delivery pipeline.

Upon next `apply`, I don't know whether the generated cert is re-used (or it is created brand-new on the Terraform machine), but it went through:
```
module.self_signed_cert_server.aws_acm_certificate.default[0]: Creating...
module.self_signed_cert_server.aws_acm_certificate.default[0]: Creation complete after 2s [id=arn:aws:acm:ap-southeast-1:XXXX:certificate/XXXX]
```

I don't know how to proceed with further debugging. I looked around and can't be sure where to locate the generated certs and which command to run for its validity period to be printed out. I'd appreciate any pointers.

## Expected Behavior
`terraform apply` will go through in **the first run** without exiting 1.

## Steps to Reproduce
I'm using an identical Terraform this to [this code](https://github.com/cloudposse/terraform-aws-ec2-client-vpn/blob/20def3f3cf6d7299fd117956da44d3f1267b6d36/main.tf#L87-L118).

## Screenshots
N/A

## Environment (please complete the following information):
- `cloudposse/ssm-tls-self-signed-cert/aws`: `0.4.0`
- Terraform v1.1.0-alpha20210908 on darwin_amd64
- provider registry.terraform.io/cloudposse/awsutils v0.8.0
- provider registry.terraform.io/hashicorp/aws v3.61.0
- provider registry.terraform.io/hashicorp/tls v3.1.0

## Additional Context
N/A

**Comment by Nuru** [comment] 2023-08-01 08:21
Closing this as invalid, since no one else reproduced it. If it happens again with the current module, you can open a new issue.

**Closed by Nuru** 2023-08-01 08:21 UTC
Labels: bug, invalid
