### ISSUE TITLE
key_algorithm attribute is readonly in tls provider v4

### ISSUE THREAD

**Issue by svalevka** [cloudposse/terraform-aws-ssm-tls-self-signed-cert#15] opened 2022-07-28 10:57 UTC
[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
key_algorithm parameter is set to readonly in the latest version of tls provider. 
This causes errors when resources using this parameter are created and `key_algorithm` is set to a variable

The provider used for creating certs is tls and its version [constraint is set](https://github.com/cloudposse/terraform-aws-ssm-tls-self-signed-cert/blob/master/versions.tf#L11) to >=3.0  . This means that version 4 will be pulled during the init . The problem is that version 4 for tls provider changes schema and adds key_algorithm  as [readonly argument](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/cert_request). Version 3 [does not have this argument](https://registry.terraform.io/providers/hashicorp/tls/3.4.0/docs/resources/cert_request) in Read-Only list

```
│ Error: Invalid Configuration for Read-Only Attribute

│   with xxxxx.self_signed_cert_ca.tls_cert_request.default,

│   on xxxxxxx.self_signed_cert_ca/main.tf line 24, in resource "tls_cert_request" "default":

│   24:   key_algorithm   = var.private_key_algorithm

│ Cannot set value for this attribute as the provider has marked it as

│ read-only. Remove the configuration line setting the value.
```

## Expected Behavior
no errors produced when `tls_cert_request` resource is created https://github.com/cloudposse/terraform-aws-ssm-tls-self-signed-cert/blob/77564a5fb3c42492e7d534376e91bf01f4876503/main.tf#L21

**Comment by Nuru** [comment] 2022-08-04 18:52
Duplicate of #13, closed by #14.

**Closed by Nuru** 2022-08-04 18:52 UTC
Labels: bug
